---
placard:
  hosts:
    placard-01:
      ansible_host: 192.168.10.50
      placard_version: "0.1.0-1"   # a v<version> GitHub Release tag, minus the v
      hdmi_rate: 50
  vars:
    ansible_user: root
